version: '3.9'

services:
  app:
    build: .
    ports:
      - "3000:3000"
    volumes:
      - .:/app
    environment:
      - DB_HOST=db
      - DB_USER=root
      - DB_PASSWORD=Snorlax1$1
      - DB_NAME=cashcontrol
    depends_on:
      - db

  db:
    image: mysql:8.0
    container_name: mysql-cashcontrol
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: Snorlax1$1
      MYSQL_DATABASE: cashcontrol
    ports:
      - "3306:3306"
    volumes:
      - mysql_data:/var/lib/mysql

volumes:
  mysql_data:
