### USUARIOS

POST http://localhost:3000/users

GET http://localhost:3000/users

DELETE http://localhost:3000/users/{id}


### transacoes


POST http://localhost:3000/users/{id}/transacoes

GET http://localhost:3000/users/{id}/transacoes

PUT  http://localhost:3000/users/{id}/transacoes/{idTransacao}

DELETE  http://localhost:3000/users/{id}/transacoes/{idTransacao}